# This file was generated by GoReleaser. DO NOT EDIT.
cask "peer" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/peer"]
  end

  version "0.1.38"

  on_macos do
    on_arm do
      sha256 "ee5dbb8f695026b6ff1c3f8ff5753bc7e85b6ba3b8ae05f75818f48e5b9c0933"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d16d7cf8cf95aea7ff78df1c3c6e7f7fed2122837ec2971b13588f976e1a19a"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_amd64.tar.gz"
    end
  end

  name "peer"
  desc "Local CLI for two coding agents pairing on one Git checkout"
  homepage "https://github.com/r13v/peer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peer"

  # No zap stanza required
end
