# This file was generated by GoReleaser. DO NOT EDIT.
cask "peer" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/peer"]
  end

  version "0.1.28"

  on_macos do
    on_arm do
      sha256 "cff7f8ffd690c3b4dc67f02f03d8e6e45b654ca265d40516aa095d586c21d5c5"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "da14b9ad0c2893933e8e682d5e058647c196716ade6e8bb14e793905440f5574"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_amd64.tar.gz"
    end
  end

  name "peer"
  desc "Local CLI for two coding agents pairing on one Git checkout"
  homepage "https://github.com/r13v/peer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peer"

  # No zap stanza required
end
