# This file was generated by GoReleaser. DO NOT EDIT.
cask "peer" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/peer"]
  end

  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "90cf77a49a690058a38aa13f886b00298fce7929fdd1d0a51807e5cca1b969fe"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d73b34963be9a9f3fcbb549193c0a065fab071e8ed583ee745bc7c381b6b981e"
      url "https://github.com/r13v/peer/releases/download/v#{version}/peer_darwin_amd64.tar.gz"
    end
  end

  name "peer"
  desc "Local CLI for two coding agents pairing on one Git checkout"
  homepage "https://github.com/r13v/peer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peer"

  # No zap stanza required
end
