# This file was generated by GoReleaser. DO NOT EDIT.
cask "plexus" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "16aeaaefcda38d14af45cb99b45dac8d00d905945cb37cdd7eb6d16d48604979"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9411cbc9721b3354e2e0ea0363a86628fcbc80a1abc0918a0b0df3dc52854fe3"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "89d051354defe8e6b8040a2d87f5eb096446b6982d7e3522de1ccd8550b3b216"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51af8d1ba0dccc03d2dc8b6ea7ce80d9be3b9f50340939ad01d9968d2a70f407"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "plexus"
  desc "Code-graph CLI: callers, neighbors, paths, communities across Go/Python/JS/TS repos"
  homepage "https://github.com/r13v/plexus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plexus"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/plexus"]
    end
  end

  # No zap stanza required

end
