# This file was generated by GoReleaser. DO NOT EDIT.
cask "plexus" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "45c1b81d29140f487b09fac2e8c0a02db9a61202d1dca50c2c43e52021ccbf76"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad812fc4eae44d83b9aa80a444e9c3c1c5dee59af52adb4f93e73cb0281a3825"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "345aae6ed0c11d9c26b9f77a7737ae489cd5bc44179eda041d8e3300a48f4719"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7fe43cdace490ec6a5d89d4fa812dacf84f2b5e3f1af8c7518f68d5473dd28e"
      url "https://github.com/r13v/plexus/releases/download/v#{version}/plexus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "plexus"
  desc "Code-graph CLI: callers, neighbors, paths, communities across Go/Python/JS/TS repos"
  homepage "https://github.com/r13v/plexus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plexus"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/plexus"]
    end
  end

  # No zap stanza required

end
