# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plexus < Formula
  desc "Code-graph CLI: callers, neighbors, paths, communities across Go/Python/JS/TS repos"
  homepage "https://github.com/r13v/plexus"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/r13v/plexus/releases/download/v0.1.0/plexus_0.1.0_darwin_amd64.tar.gz"
      sha256 "71e9d309ba43694fb34f716ed4aa997e5f240d3608004c3c6932114b64e4b52f"

      define_method(:install) do
        bin.install "plexus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/r13v/plexus/releases/download/v0.1.0/plexus_0.1.0_darwin_arm64.tar.gz"
      sha256 "51c29cc0a62efb4c21c3489a29032180dbedd9a17b57ac5a92e75ed8c953cfc3"

      define_method(:install) do
        bin.install "plexus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/r13v/plexus/releases/download/v0.1.0/plexus_0.1.0_linux_amd64.tar.gz"
      sha256 "ef7390056f49bda7ee3b9560bcad534536063206bd59b01416c6d95c1fbd7385"
      define_method(:install) do
        bin.install "plexus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/r13v/plexus/releases/download/v0.1.0/plexus_0.1.0_linux_arm64.tar.gz"
      sha256 "a83a4cde110d898e227560a8aaa9c96eb55a45ee6802f0acf6466a0d6db34353"
      define_method(:install) do
        bin.install "plexus"
      end
    end
  end

  test do
    system "#{bin}/plexus", "version"
  end
end
